stages:
  - dependencies
  - test
  - build

install_dependencies:
  image: "node:18-alpine"
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm ci
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

build:
  image: "node:18-alpine"
  stage: build
  script:
    - npm run build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

unit-tests:
  stage: test
  script:
    - npm run test:coverage
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pul

linting:
  stage: test
  script:
    - npm run lint
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pul

audit:
  stage: test
  script:
    - npm audit
