default:
  image: "node:18-alpine"
  before_script:
    - echo Hello World

cache:
  paths:
    - node_modules/

dependencies:
  stage: build
  script:
    - npm i

build:
  stage: build
  needs: [dependencies]
  script:
    - npm run build

unit-tests:
  stage: test
  script:
    - npm run test:coverage

linting:
  stage: test
  script:
    - npm run lint

audit:
  stage: test
  script:
    - npm audit
