default:
  image: "node:18-alpine"
  before_script:
    - echo Hello World

cache:
  paths:
    - node_modules/
  policy: pull

build:
  stage: build
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm ci
    - npm run build
  cache:
    - key:
      paths:
        - node_modules/
      when: on_success
      policy: pull-push

unit-tests:
  stage: test
  script:
    - npm run test:coverage

linting:
  stage: test
  script:
    - npm run lint

audit:
  stage: test
  script:
    - npm audit
