version: 0.2

env:
  variables:
    S3_ARTIFACTS_BUCKET: "source-artifacts"
    S3_ARTIFACTS_PREFIX: "source/shop-serverless"

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install

  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
#      - npm run sam:test
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
      - rm -rf serverless/__tests__
      # Remove all dependencies not needed for the Lambda deployment package (the packages from devDependencies in package.json)
#      - npm prune --production

  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template serverless/template.yaml --s3-bucket ${S3_ARTIFACTS_BUCKET} --s3-prefix ${S3_ARTIFACTS_PREFIX} --output-template template-export.yaml
      # You can use the SAM CLI command instead, however it requires previous installation on this host.
      # As it does not bring any additional value and just wraps AWS CLI's command, it's not a good practice to use it here.
#      - sam package --template serverless/template.yaml --s3-bucket $S3_ARTIFACTS_BUCKET --s3-prefix $S3_ARTIFACTS_PREFIX --output-template template-export.yaml

artifacts:
#  type: zip
  files:
    - template-export.yaml
